name: Webiosa git Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: AnY
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: Webiosa.com/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}       
        options: "--delete --asci"
